"""Official nature-of-business code masters (itr1/business_codes.py).

The module is GENERATED by tools/build_business_codes.py from the dropdown
lists hidden inside the official CBDT utilities.  These tests pin the
counts/order to the AY 2026-27 utilities and verify the builder/endpoint
integration — regressions here mean the tool drifted from the official
masters the user asked us to mirror ("implement all data as per excel").
"""

import copy
import json
import os

import pytest

from itr1 import business_codes as NOB
from itr1.errors import DataError
from itr1.itr4_builder import (BUSINESS_CODES_44AD, PROFESSION_CODES_44ADA,
                               TRANSPORT_CODES_44AE, build_itr4)
from itr1.schemakit import validate_with_schema

SAMPLE = os.path.join(os.path.dirname(__file__), "..", "samples", "sample_itr4.json")


def load_sample():
    with open(SAMPLE, encoding="utf-8") as fh:
        return json.load(fh)


def test_official_counts():
    """Counts pinned from the official AY 2026-27 utilities' dropdowns."""
    assert len(NOB.NOB_MASTER) == 356        # ITR-3 'Nature_of_Business'
    assert len(NOB.NOB_44AD) == 315          # ITR-4 BP!F13:H17 → NOB44AD
    assert len(NOB.NOB_44ADA) == 38          # ITR-4 BP!F30:H35 → NOB44ADA
    assert len(NOB.NOB_44AE) == 7            # ITR-4 BP!E5:E7 → NOB


def test_first_and_last_entries_verbatim():
    """Boundary rows of each official dropdown, verbatim order kept."""
    assert NOB.NOB_MASTER[0] == ("00001", "Share of Income from firm only")
    assert NOB.NOB_MASTER[-1][0] == "22001"
    assert NOB.NOB_44AD[0] == ("01001", "Growing and manufacturing of tea")
    assert NOB.NOB_44AD[-1][0] == "22001"
    assert NOB.NOB_44ADA[0] == ("14001", "Software development")
    assert NOB.NOB_44ADA[-1][0] == "20012"
    assert NOB.NOB_44AE[0] == ("08001", "Renting of land transport equipment")
    assert NOB.NOB_44AE[-1][0] == "11015"


def test_official_expansions_present():
    """Codes the old hand-picked lists missed — incl. 44AE 11010/11011/11012
    and late-addition codes like 16021 Social Media Influencers."""
    assert NOB.is_valid("11010", "44ae")
    assert NOB.is_valid("11011", "44ae")
    assert NOB.is_valid("11012", "44ae")
    assert NOB.is_valid("16021", "44ada")
    # FY 2025-26 addition, present in every utility's 44ADA dropdown
    assert NOB.label("16021", "44ada") == "Social Media Influencers"
    assert NOB.is_valid("21010", "44ad")     # Futures and Options trading
    assert NOB.is_valid("21011", "44ad")     # Buying and selling shares
    assert NOB.is_valid("16019_1", "44ada")  # Medical Profession (token with suffix)


def test_section_lists_are_master_subsets():
    master = set(NOB.NOB_MASTER_BY_CODE)
    for table in (NOB.NOB_44AD_BY_CODE, NOB.NOB_44ADA_BY_CODE, NOB.NOB_44AE_BY_CODE):
        assert set(table) <= master


def test_builder_aliases_export_full_lists():
    """The itr4_builder constant names the UI/tests already use now carry the
    complete official dropdowns."""
    assert len(BUSINESS_CODES_44AD) == 315
    assert len(PROFESSION_CODES_44ADA) == 38
    assert len(TRANSPORT_CODES_44AE) == 7


def test_unknown_44ad_code_rejected():
    data = load_sample()
    data["presumptive"]["44ad"][0]["code"] = "99999"
    with pytest.raises(DataError) as ei:
        build_itr4(data)
    msg = str(ei.value)
    assert "not in the official 44AD dropdown" in msg
    assert "presumptive.44ad.0.code" in msg


def test_unknown_44ada_code_rejected():
    data = load_sample()
    data["presumptive"]["44ada"][0]["code"] = "ABCDE"
    with pytest.raises(DataError) as ei:
        build_itr4(data)
    assert "not in the official 44ADA dropdown" in str(ei.value)


def test_44ad_code_must_be_business_nature():
    """A 44ADA-only profession token (or any out-of-scope token) cannot be
    used on a 44AD row — the utility dropdown scopes it the same way."""
    data = load_sample()
    data["presumptive"]["44ad"][0]["code"] = "16019_1"   # profession-only code
    with pytest.raises(DataError):
        build_itr4(data)


def test_any_official_44ad_code_builds():
    """Spot-check a few codes from distant regions of the official list —
    they must all flow into ScheduleBP and stay schema-valid."""
    for code in ("01001", "06009", "21010", "22001"):
        data = load_sample()
        data["presumptive"]["44ad"][0]["code"] = code
        out = build_itr4(data)
        row = out["json"]["ITR"]["ITR4"]["ScheduleBP"]["NatOfBus44AD"][0]
        assert row["CodeAD"] == code, code
        assert validate_with_schema("ITR4", out["json"]) == []


def test_catalog_endpoint_serves_full_lists():
    from itr1.webapp import create_app
    app = create_app()
    client = app.test_client()
    body = client.get("/api/salary/catalog").get_json()
    assert len(body["business_codes"]["44ad"]) == 315
    assert len(body["business_codes"]["44ada"]) == 38
    assert len(body["business_codes"]["44ae"]) == 7
    assert len(body["business_code_options"]["master"]) == 356
    # display options keep the utility's "<code>-<label>" shape
    assert body["business_code_options"]["44ad"][0].startswith("01001-")
