"""Import hub — parse documents downloaded from the income-tax portal and
fold them into the friendly data model.

Supports:

* **ITR JSON** (any AY, ITR-1/2/3/4 — e.g. the AY 2025-26 file downloaded
  from the e-filing portal or generated by this app): identity/details
  prefill, income-head totals for year-on-year comparison, losses carried
  forward capture.
* **AIS** (Annual Information Statement) as JSON, or the password-protected
  ZIP shipped by the portal.  ZIP password is auto-derived from the user
  profile: ``pan.lower() + DDMMYYYY`` (e.g. ``abcd1234a01011990``) with a few
  safe variants.
* **Form 26AS / Annual Tax Statement** as PDF (password = date of birth,
  ``DDMMYYYY``) or plain text: TDS (salary / non-salary / 26QC), TCS and
  advance/self-assessment challans.

All parsers are tolerant: unknown sections are reported, never fatal.
"""

from __future__ import annotations

import io
import json
import re
import zipfile

from .errors import DataError

# ---------------------------------------------------------------------------
# passwords
# ---------------------------------------------------------------------------


def _dob_digits(dob: str) -> str:
    """YYYY-MM-DD -> DDMMYYYY."""
    dob = str(dob or "").strip()
    m = re.match(r"^((?:19|20)\d{2})-(\d{2})-(\d{2})$", dob)
    if m:
        return f"{m.group(3)}{m.group(2)}{m.group(1)}"
    digits = re.sub(r"\D", "", dob)
    return digits if len(digits) == 8 else ""


def passwords_for(data: dict, kind: str) -> list[str]:
    """Candidate passwords, best first.

    kind="ais"   -> pan.lower()+DOB(DDMMYYYY), then PAN-as-typed+DOB
    kind="26as"  -> DOB(DDMMYYYY), then PAN(lower/upper)+DOB
    """
    personal = (data or {}).get("personal") or {}
    pan = str(personal.get("pan") or "").strip()
    dob = _dob_digits(personal.get("dob"))
    out: list[str] = []
    if kind == "26as":
        if dob:
            out.append(dob)
        if pan and dob:
            out.extend([pan.lower() + dob, pan.upper() + dob])
    else:  # ais zip
        if pan and dob:
            out.extend([pan.lower() + dob, pan.upper() + dob])
        if dob:
            out.append(dob)
    # de-duplicate, keep order
    seen = set()
    uniq = []
    for p in out:
        if p and p not in seen:
            uniq.append(p)
            seen.add(p)
    return uniq


# ---------------------------------------------------------------------------
# ITR JSON (prefilled / previous-year) parsing
# ---------------------------------------------------------------------------

def _walk(node, path=""):
    if isinstance(node, dict):
        for k, v in node.items():
            yield path + "/" + k, v
            yield from _walk(v, path + "/" + k)
    elif isinstance(node, list):
        for i, v in enumerate(node):
            yield from _walk(v, f"{path}[{i}]")


def _first_int(doc, *key_names, default=0):
    """First integer-ish value whose key matches any of the names (exactly)."""
    wanted = {k.lower() for k in key_names}
    for _path, v in _walk(doc):
        key = _path.rsplit("/", 1)[-1]
        key = re.sub(r"\[\d+\]$", "", key).lower()
        if key in wanted:
            try:
                return int(float(v))
            except (TypeError, ValueError):
                continue
    return default


def _first_str(doc, *key_names, default=""):
    wanted = {k.lower() for k in key_names}
    for _path, v in _walk(doc):
        key = re.sub(r"\[\d+\]$", "", _path.rsplit("/", 1)[-1]).lower()
        if key in wanted and isinstance(v, str) and v.strip():
            return v.strip()
    return default


def _get_path(doc, *names):
    """Exact key-path getter through nested dicts."""
    cur = doc
    for n in names:
        if not isinstance(cur, dict) or n not in cur:
            return None
        cur = cur[n]
    return cur


def parse_itr_json(payload) -> dict:
    """Parse any ITR JSON (our app / the portal's prefilled download).

    Returns a normalized ``summary`` used for prefill, YoY comparison and
    loss carry-forward capture.
    """
    try:
        doc = json.loads(payload) if isinstance(payload, (str, bytes)) else payload
    except (ValueError, TypeError) as exc:
        raise DataError(f"The selected file is not valid JSON ({exc}).",
                        field="ITR JSON file") from exc
    if not isinstance(doc, dict) or "ITR" not in doc:
        raise DataError("This JSON does not look like an ITR document "
                        "(missing the top-level 'ITR' object).",
                        field="ITR JSON file")
    forms = [k for k in doc["ITR"] if isinstance(doc["ITR"][k], dict)]
    form = forms[0] if forms else ""
    body = doc["ITR"].get(form, {}) if form else {}

    ay = _first_str(doc, "AssessmentYear")
    name_parts = [
        _first_str(doc, "FirstName"), _first_str(doc, "MiddleName"),
        _first_str(doc, "SurNameOrOrgName"),
    ]
    heads = {}
    if form in ("ITR1", "ITR4"):
        inc = body.get("ITR1_IncomeDeductions") or body.get("IncomeDeductions") or {}
        heads = {
            "business": inc.get("IncomeFromBusinessProf", 0),
            "salary": inc.get("IncomeFromSal", 0),
            "hp": inc.get("TotalIncomeChargeableUnHP", 0),
            "os": inc.get("IncomeOthSrc", 0)
            if isinstance(inc.get("IncomeOthSrc"), int) else 0,
            "ltcg112a": _first_int(inc, "LongCap112A"),
            "gti": inc.get("GrossTotIncomeIncLTCG112A", 0),
            "total_income": inc.get("TotalIncome", 0),
        }
    elif form == "ITR2":
        pbti = body.get("PartB-TI") or {}
        capg = pbti.get("CapGain") or {}
        heads = {
            "salary": pbti.get("Salaries", 0),
            "hp": pbti.get("IncomeFromHP", 0),
            "stcg": (capg.get("ShortTerm") or {}).get("TotalShortTerm", 0),
            "ltcg": (capg.get("LongTerm") or {}).get("TotalLongTerm", 0),
            "cg": capg.get("TotalCapGains", 0),
            "os": (pbti.get("IncFromOS") or {}).get("TotIncFromOS", 0),
            "gti": pbti.get("GrossTotalIncome", 0),
            "total_income": pbti.get("TotalIncome", 0),
            "losses_cf_declared": pbti.get("LossesOfCurrentYearCarriedFwd", 0),
        }
    elif form == "ITR3":
        pbti = body.get("PartB-TI") or {}
        heads = {
            "business": _first_int(pbti, "ProfIncGainsBus"),
            "salary": pbti.get("Salaries", 0),
            "hp": pbti.get("IncomeFromHP", 0),
            "cg": (pbti.get("CapGain") or {}).get("TotalCapGains", 0),
            "os": (pbti.get("IncFromOS") or {}).get("TotIncFromOS", 0),
            "gti": pbti.get("GrossTotalIncome", 0),
            "total_income": pbti.get("TotalIncome", 0),
        }
    else:
        heads = {"total_income": _first_int(doc, "TotalIncome"),
                 "gti": _first_int(doc, "GrossTotalIncome")}

    # taxes
    tax = {
        "total_tax_plus_interest": _first_int(doc, "AggregateTaxInterestLiability",
                                              "TotTaxPlusIntrstPay"),
        "tds": _first_int(_get_path(body, "TaxPaid") or {}, "TDS")
        or _first_int(doc, "TDS"),
        "tcs": _first_int(doc, "TCS"),
        "advance_tax": _first_int(doc, "AdvanceTax"),
        "self_assessment": _first_int(doc, "SelfAssessmentTax"),
        "refund": _first_int(doc, "RefundDue"),
        "balance_payable": _first_int(doc, "BalTaxPayable"),
    }

    # losses carried forward (ScheduleCFL for the NEXT year / current-yr not
    # set off under BFLA in this return)
    losses = {"stcg_cf": 0, "ltcg_cf": 0, "hp_cf": 0, "business_cf": 0}
    cfl = _get_path(body, "ScheduleCFL")
    if isinstance(cfl, dict):
        losses["stcg_cf"] = _first_int(cfl, "TotalAmtSTCGCL", "InStcgCurYr")
        losses["ltcg_cf"] = _first_int(cfl, "TotalAmtLTCGCL", "InLtcgCurYr")
        losses["hp_cf"] = _first_int(cfl, "CurrYrHPossCF", "TotalBFLossesCFFwd")
    if not losses["stcg_cf"]:
        losses["stcg_cf"] = _first_int(doc, "TotalAmtSTCGCL")
    if not losses["ltcg_cf"]:
        losses["ltcg_cf"] = _first_int(doc, "TotalAmtLTCGCL")

    # ---- prefill payload (identity / contact / bank / verification) ----
    pi = _get_path(body, "PartA_GEN1", "PersonalInfo") or body.get("PersonalInfo") or {}
    addr = pi.get("Address") or {}
    prefill = {
        "personal": {
            "first_name": (pi.get("AssesseeName") or {}).get("FirstName", ""),
            "middle_name": (pi.get("AssesseeName") or {}).get("MiddleName", ""),
            "last_name": (pi.get("AssesseeName") or {}).get("SurNameOrOrgName", ""),
            "pan": pi.get("PAN", ""),
            "dob": pi.get("DOB", ""),
            "aadhaar": pi.get("AadhaarCardNo", ""),
            "employer_category": pi.get("EmployerCategory", ""),
            "address": {
                "residence_no": addr.get("ResidenceNo", ""),
                "residence_name": addr.get("ResidenceName", ""),
                "road_or_street": addr.get("RoadOrStreet", ""),
                "locality_or_area": addr.get("LocalityOrArea", ""),
                "city_or_town_or_district": addr.get("CityOrTownOrDistrict", ""),
                "state_code": addr.get("StateCode", ""),
                "country_code": addr.get("CountryCode", "91"),
                "pin_code": addr.get("PinCode", ""),
                "country_code_mobile": addr.get("CountryCodeMobile", 91),
                "mobile_no": addr.get("MobileNo", ""),
                "email_address": addr.get("EmailAddress", ""),
            },
        },
        "verification": {
            "name": " ".join(p for p in name_parts if p),
            "father_name": _first_str(doc, "FatherName"),
            "pan": pi.get("PAN", ""),
            "capacity": _first_str(doc, "Capacity", default="S"),
            "place": _first_str(doc, "Place"),
        },
        "bank_accounts": [],
    }
    for _p, v in _walk(doc):
        if _p.lower().endswith("addtnlbankdetails") and isinstance(v, list):
            for b in v:
                if isinstance(b, dict) and b.get("BankAccountNo"):
                    prefill["bank_accounts"].append({
                        "ifsc": b.get("IFSCCode", ""),
                        "bank_name": b.get("BankName", ""),
                        "account_no": str(b.get("BankAccountNo", "")),
                        "account_type": b.get("AccountType", "SB"),
                        "use_for_refund": str(b.get("UseForRefund", "false")) == "true",
                    })

    return {
        "form": form,
        "assessment_year": ay,
        "name": " ".join(p for p in name_parts if p),
        "pan": pi.get("PAN", "") or _first_str(doc, "PAN"),
        "regime": ("old" if _first_str(doc, "OptOutNewTaxRegime") == "Y"
                   or _first_str(doc, "Form10IEAEarlierAYOldRegime") == "Y" else "new"),
        "heads": heads,
        "tax": tax,
        "losses": losses,
        "prefill": prefill,
        "bank_count": len(prefill["bank_accounts"]),
    }


def apply_itr_prefill(data: dict, summary: dict, sections: list[str] | None = None) -> dict:
    """Merge a parsed previous-year ITR JSON into the working data.

    sections: subset of {"personal", "bank", "verification"} — identity and
    bank are the useful, year-invariant parts.  Returns (data, notes).
    """
    import copy
    out = copy.deepcopy(data)
    notes: list[str] = []
    pre = summary.get("prefill") or {}
    wanted = set(sections or ("personal", "bank", "verification"))

    if "personal" in wanted and (pre.get("personal") or {}).get("pan"):
        old = out.get("personal") or {}
        incoming = pre["personal"]
        merged = dict(old)
        for k, v in incoming.items():
            if k == "address":
                continue
            if v and not old.get(k):
                merged[k] = v
        addr_old = old.get("address") or {}
        addr_new = dict(addr_old)
        for k, v in (incoming.get("address") or {}).items():
            if v not in ("", None) and not addr_old.get(k):
                addr_new[k] = v
        merged["address"] = addr_new
        out["personal"] = merged
        notes.append("Identity & contact details filled from the previous-year JSON "
                     "(only empty fields were touched).")
    if "bank" in wanted and pre.get("bank_accounts") and not out.get("bank_accounts"):
        out["bank_accounts"] = pre["bank_accounts"]
        notes.append(f"{len(pre['bank_accounts'])} bank account(s) imported.")
    if "verification" in wanted:
        ver_old = out.get("verification") or {}
        ver_new = dict(ver_old)
        for k, v in (pre.get("verification") or {}).items():
            if v and not ver_old.get(k):
                ver_new[k] = v
        out["verification"] = ver_new

    losses = summary.get("losses") or {}
    if any(losses.get(k) for k in ("stcg_cf", "ltcg_cf", "hp_cf", "business_cf")):
        out.setdefault("losses_cf", {})
        for k in ("stcg_cf", "ltcg_cf", "hp_cf", "business_cf"):
            if losses.get(k) and not out["losses_cf"].get(k):
                out["losses_cf"][k] = losses[k]
        notes.append("Losses carried forward captured — review the 'Losses' panel; "
                     "this return shows them in CYLA/BFLA notes (auto set-off of "
                     "b/f losses is flagged for your confirmation).")
    return out, notes


# ---------------------------------------------------------------------------
# year-on-year comparison
# ---------------------------------------------------------------------------

def year_on_year(cur_heads: dict, prev_summary: dict) -> list[dict]:
    """Compare current computation heads against the previous-year summary."""
    labels = {
        "salary": "Salary income (u/s 16)", "hp": "House property",
        "business": "Business / profession (presumptive)", "os": "Other sources",
        "ltcg112a": "LTCG u/s 112A", "stcg": "STCG (all rates)",
        "ltcg": "LTCG (all rates)", "cg": "Capital gains (total)",
        "gti": "Gross total income", "total_income": "Total income",
    }
    rows = []
    prev = prev_summary.get("heads") or {}
    for key, label in labels.items():
        cur = int(cur_heads.get(key, 0) or 0)
        old = int(prev.get(key, 0) or 0)
        if not cur and not old:
            continue
        delta = cur - old
        pct = round((delta / old) * 100, 1) if old else None
        rows.append({"head": label, "current": cur, "previous": old,
                     "delta": delta, "delta_pct": pct,
                     "trend": "up" if delta > 0 else "down" if delta < 0 else "same"})
    return rows


# ---------------------------------------------------------------------------
# AIS parsing (JSON or password ZIP)
# ---------------------------------------------------------------------------

# order matters: the first category whose keyword appears in the context wins;
# specific income families are tested before the generic tax-credit buckets so
# that e.g. a company named "TCS Ltd" cannot misfile a dividend as TCS.
_AIS_CATEGORIES = [
    ("tds_salary", ("tds on salary", "salary-tds", "tds u/s 192", "192")),
    ("interest_savings", ("interest from savings", "savings bank interest")),
    ("interest_deposit", ("interest from deposit", "interest from fixed deposit",
                          "term deposit interest")),
    ("dividend", ("dividend",)),
    ("rent", ("rent received", "rental income")),
    ("salary", ("salary", "sft-012 employer", "sft-013")),
    ("tcs", ("tax collected", "tcs amount", "tcs u/s", "206c")),
    ("tds_other", ("tax deducted", "tds", "194")),
    ("advance_tax", ("advance tax", "self assessment", "self-assessment",
                     "payment of taxes", "tax payment", "self assessment tax")),
    ("mf_sale", ("mutual fund units", "sale of securities", "purchase of securities",
                 "units of mutual fund")),
    ("property_txn", ("immovable property", "transfer of immovable")),
    ("foreign", ("foreign remittance", "forex")),
    ("cash", ("cash deposit", "cash withdrawal", "cash payment")),
    ("turnover", ("turnover", "business receipts", "gross receipts")),
    ("other", ("",)),
]


def _classify(text: str):
    t = text.lower()
    for cat, keys in _AIS_CATEGORIES:
        if any(k and k in t for k in keys):
            return cat
    return "other"


def parse_ais_json(doc) -> dict:
    """Generic walker over any AIS JSON layout; buckets records by context."""
    entries: list[dict] = []
    ay = str(doc.get("assessmentYear") or doc.get("AssessmentYear")
             or doc.get("AY") or "") if isinstance(doc, dict) else ""

    def visit(node, ctx: list[str]):
        if isinstance(node, dict):
            amount_keys = [k for k in node
                           if k.lower() in ("amount", "transactionamount", "paidamount",
                                            "grossamount", "tdsamount", "tcsamount",
                                            "taxdeducted", "taxcollected") and
                           isinstance(node[k], (int, float, str))]
            if amount_keys and not any(isinstance(v, (list, dict)) for v in node.values()):
                amt = 0.0
                for k in amount_keys:
                    try:
                        amt = float(str(node[k]).replace(",", "") or 0)
                        break
                    except ValueError:
                        continue
                desc = " / ".join(str(node.get(k, "")) for k in
                                  ("informationDescription", "description",
                                   "informationSource", "sourceDescription",
                                   "name", "deductorName") if node.get(k))
                context = " > ".join(ctx + [desc])
                entries.append({
                    "category": _classify(context),
                    "description": desc or ctx[-1] if ctx else desc or "AIS entry",
                    "context": context,
                    "amount": amt,
                    "date": str(node.get("transactionDate") or node.get("informationDate")
                                or node.get("date") or ""),
                    "fields": {k: v for k, v in node.items()
                               if not isinstance(v, (list, dict))},
                })
            for k, v in node.items():
                visit(v, ctx + [str(k)])
        elif isinstance(node, list):
            for item in node:
                visit(item, ctx)

    if isinstance(doc, dict):
        visit(doc, [])
    return {"assessment_year": ay, "entries": entries}


def _read_zip(passwords: list[str], blob: bytes) -> bytes:
    zf = zipfile.ZipFile(io.BytesIO(blob))
    json_names = [n for n in zf.namelist() if n.lower().endswith(".json")]
    names = json_names or zf.namelist()
    if not names:
        raise DataError("The ZIP archive is empty.", field="AIS file")
    last_err: Exception | None = None
    for pwd in passwords:
        try:
            return zf.read(names[0], pwd=pwd.encode())
        except RuntimeError as exc:          # bad password
            last_err = exc
            continue
    raise DataError("Could not unlock the AIS ZIP — password did not match. "
                    "It is usually your PAN (lower case) followed by date of birth "
                    "in DDMMYYYY, e.g. abcd1234a01011990.",
                    field="AIS password") from last_err


def parse_ais(blob: bytes, filename: str, data: dict) -> dict:
    """Parse AIS from raw JSON text or the portal's password ZIP."""
    name = (filename or "").lower()
    if name.endswith(".zip") or blob[:2] == b"PK":
        pwds = passwords_for(data, "ais")
        if not pwds:
            raise DataError("Fill your PAN and date of birth first — they form the "
                            "AIS file password.", field="AIS password")
        blob = _read_zip(pwds, blob)
    try:
        doc = json.loads(blob.decode("utf-8", "replace"))
    except ValueError as exc:
        raise DataError("The AIS content is not valid JSON — upload the JSON or "
                        "the ZIP exactly as downloaded.", field="AIS file") from exc
    out = parse_ais_json(doc)
    out["password_used"] = bool(name.endswith(".zip") or blob[:2] == b"PK")
    return out


# ---------------------------------------------------------------------------
# Form 26AS (PDF / TXT)
# ---------------------------------------------------------------------------

_TAN_RE = r"[A-Z]{4}[0-9]{5}[A-Z]"
_NUM = r"[\d,]+(?:\.\d{1,2})?"


def _num(txt: str) -> int:
    try:
        return int(round(float(str(txt).replace(",", ""))))
    except (ValueError, TypeError):
        return 0


def parse_26as_text(text: str) -> dict:
    """Parse the classic 26AS text layout (also the text extracted from PDFs)."""
    tds_salary, tds_other, tds_rent, tcs, challans, refunds = [], [], [], [], [], []
    section_ctx = ""
    for raw in text.splitlines():
        line = " ".join(raw.split())
        if not line:
            continue
        low = line.lower()
        if "part-a1" in low or "part a1" in low:
            section_ctx = "salary"
        elif "part-a2" in low or "part a2" in low:
            section_ctx = "other"
        elif "part-b" in low and "tcs" in low:
            section_ctx = "tcs"
        elif "part-c" in low or "advance tax" in low or "self assessment" in low:
            section_ctx = "challan"
        elif "refund" in low:
            section_ctx = "refund"

        tans = re.findall(_TAN_RE, line)
        nums = [_num(n) for n in re.findall(_NUM, line)]
        bsr = re.search(r"\b(0\d{6})\b", line)
        date_m = re.search(r"\b(\d{2}[-/][A-Za-z]{3}[-/]\d{4}|\d{4}-\d{2}-\d{2}|"
                           r"\d{2}[-/]\d{2}[-/]\d{4})\b", line)
        sec_m = re.search(r"\b(19[24][A-Z0-9-]*|206[A-Z0-9-]*)\b", line)

        if bsr and len(nums) >= 1 and date_m:
            challans.append({"bsr_code": bsr.group(1), "date": _norm_date(date_m.group(1)),
                             "challan_no": nums[1] if len(nums) > 1 else 0,
                             "amount": nums[-1]})
            continue
        if tans and len(nums) >= 2:
            sec = sec_m.group(1) if sec_m else ""
            name_m = re.split(_TAN_RE, line)[0].strip(" .,-")
            is_tcs = section_ctx == "tcs" or sec.startswith("206")
            row = {
                "tan": tans[0],
                "name": name_m[-60:] or ("Collector" if is_tcs else "Deductor"),
                "section": sec or ("194A" if not is_tcs else "206C"),
                "amount_paid": nums[-2] if len(nums) >= 3 else 0,
                "tax": nums[-1],
                "year": _infer_year(line),
            }
            if is_tcs:
                tcs.append(row)
            elif "rent" in low or sec in ("194-IB", "194IB"):
                tds_rent.append(row)
            elif section_ctx == "salary" or sec == "192":
                tds_salary.append(row)
            else:
                tds_other.append(row)
            continue
        if section_ctx == "refund" and nums and "refund" in low:
            refunds.append({"amount": nums[-1], "description": line[:120]})
    return {"tds_salary": tds_salary, "tds_others": tds_other, "tds_rent": tds_rent,
            "tcs": tcs, "challans": challans, "refunds": refunds}


def _norm_date(s: str) -> str:
    s = s.strip()
    m = re.match(r"(\d{2})[-/]([A-Za-z]{3})[-/](\d{4})", s)
    months = {"jan": "01", "feb": "02", "mar": "03", "apr": "04", "may": "05",
              "jun": "06", "jul": "07", "aug": "08", "sep": "09", "oct": "10",
              "nov": "11", "dec": "12"}
    if m:
        return f"{m.group(3)}-{months.get(m.group(2).lower(), '01')}-{m.group(1)}"
    m = re.match(r"(\d{2})[-/](\d{2})[-/](\d{4})", s)
    if m:
        return f"{m.group(3)}-{m.group(2)}-{m.group(1)}"
    return s


def _infer_year(line: str) -> int:
    m = re.search(r"\b(20[12]\d)\b", line)
    return int(m.group(1)) if m else 2025


def parse_26as(blob: bytes, filename: str, data: dict) -> dict:
    """Form 26AS from PDF (password = DOB) or text."""
    name = (filename or "").lower()
    text = ""
    used_password = ""
    if name.endswith(".pdf") or blob[:4] == b"%PDF":
        try:
            from pypdf import PdfReader
        except ImportError as exc:  # pragma: no cover
            raise DataError("PDF support is unavailable on this server.",
                            field="26AS file") from exc
        reader = PdfReader(io.BytesIO(blob))
        if reader.is_encrypted:
            pwds = passwords_for(data, "26as")
            if not pwds:
                raise DataError("Fill your date of birth first — the 26AS PDF "
                                "password is DOB in DDMMYYYY.", field="26AS password")
            ok = False
            for pwd in pwds:
                try:
                    if reader.decrypt(pwd):
                        used_password = pwd
                        ok = True
                        break
                except Exception:                       # noqa: BLE001
                    continue
            if not ok:
                raise DataError("Could not unlock the 26AS PDF — password should be "
                                "your date of birth in DDMMYYYY.",
                                field="26AS password")
        parts = []
        for page in reader.pages:
            parts.append(page.extract_text() or "")
        text = "\n".join(parts)
    else:
        text = blob.decode("utf-8", "replace")
    if len(text.strip()) < 20:
        raise DataError("No readable text found in the 26AS file.",
                        field="26AS file")
    out = parse_26as_text(text)
    out["password_used"] = bool(used_password)
    out["raw_lines"] = max(0, len(text.splitlines()) - 1)
    return out


# ---------------------------------------------------------------------------
# fold parsed credits into the working data
# ---------------------------------------------------------------------------

def apply_26as(data: dict, parsed: dict, kinds: list[str] | None = None) -> tuple[dict, list[str]]:
    """Merge 26AS/AIS tax credits into ``data['tax_paid']``.

    kinds subsets: "tds_salary", "tds_others", "tds_rent", "tcs", "challans".
    Duplicates (same TAN+section+amount) are skipped.
    """
    import copy
    out = copy.deepcopy(data)
    tp = out.setdefault("tax_paid", {})
    notes: list[str] = []
    kinds = kinds or ["tds_salary", "tds_others", "tds_rent", "tcs", "challans"]

    def seen(rows, key):
        return {(str(r.get(key[0])), str(r.get(key[1])), int(r.get(key[2]) or 0))
                for r in rows}

    if "tds_salary" in kinds:
        rows = tp.setdefault("tds_on_salary", [])
        have = seen(rows, ("tan", "employer_name", "tds"))
        added = 0
        for r in parsed.get("tds_salary", []):
            sig = (r["tan"], r["name"], r["tax"])
            if sig in have or r["tax"] <= 0:
                continue
            rows.append({"tan": r["tan"], "employer_name": r["name"],
                         "salary_income": r.get("amount_paid", 0), "tds": r["tax"]})
            have.add(sig)
            added += 1
        if added:
            notes.append(f"{added} salary TDS row(s) added.")
    if "tds_others" in kinds:
        rows = tp.setdefault("tds_others", [])
        have = seen(rows, ("tan", "section", "tds_deducted"))
        added = 0
        for r in parsed.get("tds_others", []):
            sig = (r["tan"], r["section"], r["tax"])
            if sig in have or r["tax"] <= 0:
                continue
            rows.append({"tan": r["tan"], "deductor_name": r["name"],
                         "section": r["section"] or "94A",
                         "amount_paid": r.get("amount_paid", 0),
                         "tds_deducted": r["tax"], "tds_claimed": r["tax"]})
            have.add(sig)
            added += 1
        if added:
            notes.append(f"{added} non-salary TDS row(s) added.")
    if "tds_rent" in kinds:
        rows = tp.setdefault("tds3", [])
        added = 0
        for r in parsed.get("tds_rent", []):
            if r["tax"] <= 0:
                continue
            rows.append({"tenant_pan": "", "tenant_name": r["name"],
                         "gross_receipt": r.get("amount_paid", 0),
                         "tds_deducted": r["tax"], "tds_claimed": r["tax"]})
            added += 1
        if added:
            notes.append(f"{added} TDS-on-rent (26QC) row(s) added.")
    if "tcs" in kinds:
        rows = tp.setdefault("tcs", [])
        have = seen(rows, ("tan", "collector_name", "tcs_collected"))
        added = 0
        for r in parsed.get("tcs", []):
            sig = (r["tan"], r["name"], r["tax"])
            if sig in have or r["tax"] <= 0:
                continue
            rows.append({"tan": r["tan"], "collector_name": r["name"],
                         "amount_subject": r.get("amount_paid", 0),
                         "tcs_collected": r["tax"], "tcs_claimed": r["tax"]})
            have.add(sig)
            added += 1
        if added:
            notes.append(f"{added} TCS row(s) added.")
    if "challans" in kinds:
        rows = tp.setdefault("challans", [])
        have = {(str(r.get("bsr_code")), str(r.get("date")), int(r.get("amount") or 0))
                for r in rows}
        added = 0
        for c in parsed.get("challans", []):
            sig = (c["bsr_code"], c.get("date", ""), c["amount"])
            if sig in have or c["amount"] <= 0:
                continue
            rows.append({"bsr_code": c["bsr_code"], "date": c.get("date", ""),
                         "challan_no": c.get("challan_no", 0), "amount": c["amount"]})
            have.add(sig)
            added += 1
        if added:
            notes.append(f"{added} advance/self-assessment challan(s) added.")
    return out, notes


# ---------------------------------------------------------------------------
# AIS -> income candidates + comparison vs computation
# ---------------------------------------------------------------------------

_AIS_INCOME_MAP = {
    "interest_savings": {"nature": "SAV", "label": "Savings bank interest (AIS)"},
    "interest_deposit": {"nature": "IFD", "label": "Interest on deposits (AIS)"},
    "dividend": {"nature": "DIV", "label": "Dividend (AIS)"},
    "other": {"nature": "OTH", "label": "Other income (AIS)"},
}


def ais_income_candidates(ais: dict) -> list[dict]:
    """Income entries from AIS that can be pushed into the return with one tap."""
    out = []
    for i, e in enumerate(ais.get("entries", [])):
        cat = e["category"]
        if cat in _AIS_INCOME_MAP and e["amount"] > 0:
            m = _AIS_INCOME_MAP[cat]
            out.append({
                "id": i, "category": cat, "amount": int(round(e["amount"])),
                "description": e["description"], "date": e["date"],
                "target": {"list": "other_sources",
                           "row": {"nature": m["nature"], "amount": int(round(e["amount"])),
                                   "description": f'{m["label"]}: {e["description"]}'}},
            })
        elif cat == "salary" and e["amount"] > 0:
            out.append({
                "id": i, "category": "salary", "amount": int(round(e["amount"])),
                "description": e["description"], "date": e["date"],
                "target": {"list": "salary_box", "row": {"salary_17_1": int(round(e["amount"]))}},
            })
    return out


def apply_ais_items(data: dict, candidates: list[dict], ids: list[int]) -> tuple[dict, list[str]]:
    """Add the chosen AIS incomes into the working data (tap-to-add)."""
    import copy
    out = copy.deepcopy(data)
    notes: list[str] = []
    want = set(ids)
    for c in candidates:
        if c["id"] not in want:
            continue
        t = c["target"]
        if t["list"] == "other_sources":
            rows = out.setdefault("other_sources", [])
            dup = any(r.get("nature") == t["row"]["nature"]
                      and int(r.get("amount") or 0) == t["row"]["amount"]
                      and t["row"]["description"][:20] in str(r.get("description", ""))
                      for r in rows)
            if not dup:
                rows.append(dict(t["row"]))
                notes.append(f"Added {t['row']['description']} — Rs. {c['amount']:,}.")
        elif t["list"] == "salary_box":
            sal = out.setdefault("salary", {})
            existing = int(sal.get("salary_17_1") or 0)
            if existing == t["row"]["salary_17_1"]:
                continue
            if existing:
                sal["salary_17_1"] = max(existing, t["row"]["salary_17_1"])
                notes.append("Salary box updated to the AIS figure (higher of "
                             "existing/AIS kept).")
            else:
                sal["salary_17_1"] = t["row"]["salary_17_1"]
                notes.append(f"Salary of Rs. {c['amount']:,} added from AIS.")
    if not notes:
        notes.append("Nothing new to add (already present or nothing selected).")
    return out, notes


def compare_with_ais(data: dict, ais: dict, computed: dict) -> list[dict]:
    """Side-by-side of AIS totals vs our computation, per income family.

    ``computed`` is the report dict of the current build (any ITR form).
    """
    totals: dict[str, float] = {}
    for e in ais.get("entries", []):
        totals[e["category"]] = totals.get(e["category"], 0.0) + e["amount"]

    os_rows = data.get("other_sources") or []

    def os_amount(*natures):
        return sum(int(r.get("amount") or 0) for r in os_rows
                   if str(r.get("nature")) in natures)

    sal = (data.get("salary") or {})
    try:
        salary_box = float(sal.get("salary_17_1") or 0)
    except (TypeError, ValueError):
        salary_box = 0
    if not salary_box:
        salary_box = sum(float(c.get("amount") or 0)
                         for c in sal.get("components") or [])

    hp = 0.0
    for p in data.get("house_properties") or []:
        try:
            hp += float(p.get("annual_lettable_value") or 0)
        except (TypeError, ValueError):
            continue

    mapping = [
        ("Salary", "salary", salary_box),
        ("Interest (savings + deposits)", "interest",
         os_amount("SAV", "IFD", "INT", "TAX")),
        ("Dividend", "dividend", os_amount("DIV")),
        ("Rent received", "rent", hp),
    ]
    rows = []
    for label, cat, ours in mapping:
        ais_amt = (totals.get(cat, 0.0)
                   + (totals.get("interest_savings", 0.0)
                      + totals.get("interest_deposit", 0.0) if cat == "interest" else 0.0))
        ais_amt = int(round(ais_amt))
        ours = int(round(ours))
        if not ais_amt and not ours:
            continue
        diff = ours - ais_amt
        if ais_amt == ours:
            status = "matched"
        elif ours > ais_amt:
            status = "return higher" if ais_amt else "missing in AIS"
        else:
            status = "AIS higher — review" if ours else "missing in return"
        rows.append({"head": label, "ais": ais_amt, "return": ours,
                     "difference": diff, "status": status})
    return rows
