"""ITR-4 (SUGAM) JSON builder — AY 2026-27, official schema V1.1.

For resident individuals / HUF / firms with presumptive business income
u/s 44AD (small business — 8% cash / 6% digital of turnover), 44ADA
(specified professions — 50% of gross receipts) and 44AE (goods carriages —
per-vehicle rates), plus salary / one house property / other sources, with
total income ≤ Rs. 50 lakh.

The friendly input model adds a ``presumptive`` block::

    "presumptive": {
      "44ad":  [{"name": "General Store", "code": "09028",
                 "gross_turnover": 4000000, "turnover_bank": 3000000,
                 "turnover_cash": 800000, "turnover_other": 200000,
                 "income_declared": 0}],
      "44ada": [{"name": "Medical practice", "code": "16019_1",
                 "gross_receipts": 1800000, "receipts_bank": 1800000,
                 "receipts_cash": 0, "receipts_other": 0,
                 "income_declared": 0}],
      "44ae":  {"vehicles": [{"reg_no": "GJ05AB1234", "owned": "OWN",
                              "tonnage": 9, "months": 12, "heavy": false}]},
      "financials": {"sundry_debtors": 120000, "cash_in_hand": 45000, ...}
    }
"""

from __future__ import annotations

import copy

from . import (SW_CREATED_BY, UTILITY_SW_VERSION_BY_FORM,
               UTILITY_FORM_DESCRIPTION)
from . import business_codes as NOB
from . import constants as C
from . import tax_engine as T
from . import salaryx as SX
from .builder import (_build_salary, _build_house_property, _build_other_sources,
                      _build_exempt_income, _build_vi_a, _build_tax_paid,
                      _g, _s, TODAY)
from .errors import DataError, field_scope, reset_scopes
from .schemakit import load_schema

D4 = load_schema("ITR4")["definitions"]


def _resolve(node):
    while isinstance(node, dict) and "$ref" in node:
        node = D4[node["$ref"].split("/")[-1]]
    return node if isinstance(node, dict) else {}


_ITR4_PROPS = set((_resolve(D4["ITR"]["properties"]["ITR4"]).get("properties") or {}))
_INCDED = _resolve(_resolve(D4["ITR"]["properties"]["ITR4"])["properties"]["IncomeDeductions"])
_USR_VIA_PROPS = set((_resolve(_INCDED["properties"]["UsrDeductUndChapVIA"])
                      .get("properties") or {}))
_ELIG_VIA_PROPS = set((_resolve(_INCDED["properties"]["DeductUndChapVIA"])
                       .get("properties") or {}))

TURNOVER_CAP_ITR4 = 5_000_000  # total-income ceiling of Rs. 50 lakh for ITR-4

RATE_44AD_DIGITAL = 0.06
RATE_44AD_CASH = 0.08
RATE_44ADA = 0.50
RATE_44AE_LIGHT = 7500          # per vehicle per month
RATE_44AE_HEAVY_PER_TON = 1000  # per ton per month (>12 MT)
HEAVY_TONNAGE = 12
TURNOVER_CAP_44AD = 30000000    # ₹3 crore
RECEIPTS_CAP_44ADA = 7500000    # ₹75 lakh

# Official nature-of-business code masters, extracted verbatim from the
# dropdown lists hidden inside the CBDT Excel utilities (ITR-4 'DB' sheet;
# see itr1/business_codes.py — generated by tools/build_business_codes.py
# and pinned by tests/test_business_codes.py / test_master_list_parity.py).
# The full per-section lists (315 codes for 44AD, 38 for 44ADA, 7 for 44AE)
# are what the official dropdowns offer; any other code is rejected below.
BUSINESS_CODES_44AD = NOB.NOB_44AD_BY_CODE
PROFESSION_CODES_44ADA = NOB.NOB_44ADA_BY_CODE
TRANSPORT_CODES_44AE = NOB.NOB_44AE_BY_CODE


def _check_nob_code(code: str, scope: str, catalog: dict, field: str) -> str:
    """Validate a presumptive nature-of-business code like the official
    utility does (dropdown = its hidden master list)."""
    code = str(code or "")
    if code in catalog:
        return code
    raise DataError(
        f"{field}: nature-of-business code {code!r} is not in the official "
        f"{scope} dropdown ({len(catalog)} codes shipped in the CBDT "
        f"utility).  Pick a code from the official list — e.g. " +
        ", ".join(f"{c} ({catalog[c]})" for c in list(catalog)[:3]) +
        " — see GET /api/salary/catalog → business_codes.")



def _creation_block(creation_info) -> dict:
    ci = dict(creation_info or {})
    by = ci.get("sw_created_by", SW_CREATED_BY)
    return {
        "SWVersionNo": str(ci.get("sw_version", UTILITY_SW_VERSION_BY_FORM["ITR4"])),
        "SWCreatedBy": by,
        "JSONCreatedBy": by,
        "JSONCreationDate": str(ci.get("creation_date", TODAY())),
        "IntermediaryCity": str(ci.get("intermediary_city", "Delhi")),
        "Digest": str(ci.get("digest", "-")),
    }


def _personal_info(data) -> dict:
    personal = data.get("personal", {}) or {}
    addr_in = personal.get("address", {}) or {}
    addr = {
        "ResidenceNo": _s(addr_in, "residence_no"),
        "ResidenceName": _s(addr_in, "residence_name"),
        "RoadOrStreet": _s(addr_in, "road_or_street"),
        "LocalityOrArea": _s(addr_in, "locality_or_area"),
        "CityOrTownOrDistrict": _s(addr_in, "city_or_town_or_district"),
        "StateCode": _s(addr_in, "state_code"),
        "CountryCode": _s(addr_in, "country_code", "91"),
        "CountryCodeMobile": _g(addr_in, "country_code_mobile", 91),
        "MobileNo": _g(addr_in, "mobile_no"),
        "EmailAddress": _s(addr_in, "email_address"),
    }
    if _g(addr_in, "mobile_no_sec"):
        addr["CountryCodeMobileNoSec"] = _g(
            addr_in, "country_code_mobile_sec", 91)
        addr["MobileNoSec"] = _g(addr_in, "mobile_no_sec")
    if _s(addr_in, "email_address_sec"):
        addr["EmailAddressSec"] = _s(addr_in, "email_address_sec")
    pin = _g(addr_in, "pin_code")
    if pin:
        addr["PinCode"] = pin
    pi = {
        "AssesseeName": {
            "FirstName": _s(personal, "first_name"),
            "MiddleName": _s(personal, "middle_name"),
            "SurNameOrOrgName": _s(personal, "last_name") or _s(personal, "first_name"),
        },
        "PAN": _s(personal, "pan"),
        "Address": addr,
        "DOB": _s(personal, "dob") or "1990-01-01",
        "EmployerCategory": _s(personal, "employer_category", "NA"),
        "Status": _s(personal, "status") or "I",
    }
    # secondary address (utility: 'Is the secondary address same as primary?')
    secondary_same = personal.get("secondary_address_same", True)
    pi["SecondaryAdd"] = "Y" if secondary_same else "N"
    if not secondary_same:
        alt_in = personal.get("alternate_address", {}) or {}
        alt = {
            "ResidenceNo": _s(alt_in, "residence_no"),
            "ResidenceName": _s(alt_in, "residence_name"),
            "RoadOrStreet": _s(alt_in, "road_or_street"),
            "LocalityOrArea": _s(alt_in, "locality_or_area"),
            "CityOrTownOrDistrict": _s(alt_in, "city_or_town_or_district"),
            "StateCode": _s(alt_in, "state_code"),
            "CountryCode": _s(alt_in, "country_code", "91"),
        }
        alt = {k: v for k, v in alt.items() if v not in ("", None)}
        alt["PinCode"] = _g(alt_in, "pin_code")
        pi["AlternateAddress"] = alt
    if not pi["AssesseeName"]["MiddleName"]:
        pi["AssesseeName"].pop("MiddleName")
    if _s(personal, "aadhaar"):
        pi["AadhaarCardNo"] = _s(personal, "aadhaar")
    return pi


def _filing_status_itr4(data, warnings) -> dict:
    filing = data.get("filing", {}) or {}
    return_section = _g(filing, "return_section", 11)
    opt_out = bool(filing.get("opt_out_new_regime"))
    fs = {
        "ReturnFileSec": return_section,
        "Form10IEAEarlierAYOldRegime": "Y" if opt_out else "N",
        "AsseseeRepFlg": "Y" if filing.get("is_representative") else "N",
        "ItrFilingDueDate": "2026-08-31",
    }
    if opt_out:
        fs["F10IEACurrAYOldRegime"] = "Y"
        warnings.append("Old regime with business income requires Form 10-IEA to be "
                        "filed before the return due date — confirm it is filed "
                        "(tracked as F10IEACurrAYOldRegime=Y).")
    if return_section == 17:
        fs["ReceiptNo"] = _s(filing, "original_receipt_no")
        fs["OrigRetFiledDate"] = _s(filing, "original_filing_date")
    if return_section in (13, 14, 16, 18):
        fs["NoticeNo"] = _s(filing, "notice_no")
        fs["NoticeDateUnderSec"] = _s(filing, "notice_date")
    return fs


# ---------------------------------------------------------------------------
# presumptive income (ScheduleBP)
# ---------------------------------------------------------------------------

def compute_presumptive(data: dict) -> dict:
    """Compute presumptive income; returns input echo + computed numbers."""
    pre = data.get("presumptive") or {}
    warnings: list[str] = []

    # --- 44AD ---
    rows_44ad = []
    tot_turnover = tot_bank = tot_cash = tot_other = 0
    for i, r in enumerate(pre.get("44ad") or [], 1):
        with field_scope(f"44AD business {i} ({r.get('name') or 'business'})",
                         f"presumptive.44ad.{i - 1}"):
            turnover = _g(r, "gross_turnover")
            bank = _g(r, "turnover_bank")
            cash = _g(r, "turnover_cash")
            other = _g(r, "turnover_other")
            declared = _g(r, "income_declared")
        if bank + cash + other > turnover:
            warnings.append(f"44AD '{r.get('name')}': bank+cash+other receipts exceed "
                            "gross turnover; other mode adjusted to balance.")
            other = max(0, turnover - bank - cash)
        if turnover and not (bank + cash + other):
            other = turnover
        presumptive = round((bank + other) * RATE_44AD_DIGITAL + cash * RATE_44AD_CASH)
        income = max(declared, presumptive)
        if declared and declared < presumptive:
            warnings.append(f"44AD '{r.get('name')}': declared income Rs. {declared:,} is "
                            f"below presumptive Rs. {presumptive:,} — presumptive applied "
                            "(lower declaration needs books + audit u/s 44AB).")
        rows_44ad.append({
            "name": str(r.get("name") or f"Business {i}"),
            "code": _check_nob_code(r.get("code") or "09028", "44AD",
                                    BUSINESS_CODES_44AD,
                                    f"presumptive.44ad.{i - 1}.code"),
            "description": str(r.get("description") or ""),
            "gross_turnover": turnover, "turnover_bank": bank, "turnover_cash": cash,
            "turnover_other": other, "presumptive_income": presumptive,
            "income": income,
        })
        tot_turnover += turnover
        tot_bank += bank
        tot_cash += cash
        tot_other += other
    if tot_turnover > TURNOVER_CAP_44AD:
        warnings.append(f"44AD turnover Rs. {tot_turnover:,} exceeds the Rs. 3,00,00,000 "
                        "limit (Rs. 3 cr applies only if cash receipts ≤ 5%) — ITR-3 may "
                        "be required with audit.")
    inc_44ad = sum(r["income"] for r in rows_44ad)

    # --- 44ADA ---
    rows_44ada = []
    tot_receipts = 0
    for i, r in enumerate(pre.get("44ada") or [], 1):
        with field_scope(f"44ADA profession {i} ({r.get('name') or 'profession'})",
                         f"presumptive.44ada.{i - 1}"):
            receipts = _g(r, "gross_receipts")
            bank = _g(r, "receipts_bank")
            cash = _g(r, "receipts_cash")
            other = _g(r, "receipts_other")
            declared = _g(r, "income_declared")
        if bank + cash + other > receipts:
            warnings.append(f"44ADA '{r.get('name')}': receipt split exceeds gross "
                            "receipts; other mode adjusted.")
            other = max(0, receipts - bank - cash)
        if receipts and not (bank + cash + other):
            bank = receipts
        presumptive = round(receipts * RATE_44ADA)
        income = max(declared, presumptive)
        if declared and declared < presumptive:
            warnings.append(f"44ADA '{r.get('name')}': declared income below 50% of "
                            "receipts — presumptive applied (lower needs audit).")
        rows_44ada.append({
            "name": str(r.get("name") or f"Profession {i}"),
            "code": _check_nob_code(r.get("code") or "14001", "44ADA",
                                    PROFESSION_CODES_44ADA,
                                    f"presumptive.44ada.{i - 1}.code"),
            "description": str(r.get("description") or ""),
            "gross_receipts": receipts, "receipts_bank": bank, "receipts_cash": cash,
            "receipts_other": other, "presumptive_income": presumptive,
            "income": income,
        })
        tot_receipts += receipts
    if tot_receipts > RECEIPTS_CAP_44ADA:
        warnings.append(f"44ADA receipts Rs. {tot_receipts:,} exceed Rs. 75,00,000 — "
                        "ITR-3 required (audit applies).")
    inc_44ada = sum(r["income"] for r in rows_44ada)

    # --- 44AE ---
    ae_in = pre.get("44ae") or {}
    rows_44ae = []
    for i, v in enumerate(ae_in.get("vehicles") or [], 1):
        with field_scope(f"Goods carriage {i} ({v.get('reg_no') or 'vehicle'})",
                         f"presumptive.44ae.vehicles.{i - 1}"):
            months = min(12, max(1, _g(v, "months", 12)))
            tonnage = _g(v, "tonnage")
        heavy = bool(v.get("heavy")) or tonnage > HEAVY_TONNAGE
        if heavy:
            income = RATE_44AE_HEAVY_PER_TON * max(1, tonnage) * months
        else:
            income = RATE_44AE_LIGHT * months
        rows_44ae.append({
            "reg_no": str(v.get("reg_no") or ""),
            "owned": str(v.get("owned") or "OWN"),
            "tonnage": tonnage if heavy else 0,
            "months": months,
            "heavy": heavy,
            "income": income,
        })
    inc_44ae = sum(r["income"] for r in rows_44ae)

    total = inc_44ad + inc_44ada + inc_44ae
    return {
        "44ad_rows": rows_44ad, "44ada_rows": rows_44ada, "44ae_rows": rows_44ae,
        "44ad_income": inc_44ad, "44ada_income": inc_44ada, "44ae_income": inc_44ae,
        "total_income": total,
        "totals": {"44ad_turnover": tot_turnover, "44ad_bank": tot_bank,
                   "44ad_cash": tot_cash, "44ad_other": tot_other,
                   "44ada_receipts": tot_receipts},
        "warnings": warnings,
        "financials": pre.get("financials") or {},
    }


def _schedule_bp(pres: dict) -> dict | None:
    if not (pres["44ad_rows"] or pres["44ada_rows"] or pres["44ae_rows"]):
        return None
    t = pres["totals"]
    bp: dict = {}
    if pres["44ad_rows"]:
        bp["NatOfBus44AD"] = [
            {"NameOfBusiness": r["name"], "CodeAD": r["code"],
             **({"Description": r["description"]} if r["description"] else {})}
            for r in pres["44ad_rows"]]
        bp["PersumptiveInc44AD"] = {
            "GrsTotalTrnOver": t["44ad_turnover"],
            "GrsTrnOverBank": t["44ad_bank"],
            "GrsTotalTrnOverInCash": t["44ad_cash"],
            "GrsTrnOverAnyOthMode": t["44ad_other"],
            "PersumptiveInc44AD6Per": round((t["44ad_bank"] + t["44ad_other"])
                                            * RATE_44AD_DIGITAL),
            "PersumptiveInc44AD8Per": round(t["44ad_cash"] * RATE_44AD_CASH),
            "TotPersumptiveInc44AD": pres["44ad_income"],
        }
    if pres["44ada_rows"]:
        bp["NatOfBus44ADA"] = [
            {"NameOfBusiness": r["name"], "CodeADA": r["code"],
             **({"Description": r["description"]} if r["description"] else {})}
            for r in pres["44ada_rows"]]
        bp["PersumptiveInc44ADA"] = {
            "GrsReceipt": t["44ada_receipts"],
            "GrsTrnOverBank44ADA": sum(r["receipts_bank"] for r in pres["44ada_rows"]),
            "GrsTotalTrnOverInCash44ADA": sum(r["receipts_cash"] for r in pres["44ada_rows"]),
            "GrsTrnOverAnyOthMode44ADA": sum(r["receipts_other"] for r in pres["44ada_rows"]),
            "TotPersumptiveInc44ADA": pres["44ada_income"],
        }
    if pres["44ae_rows"]:
        bp["NatOfBus44AE"] = [{"NameOfBusiness": "Plying/hiring goods carriages",
                               "CodeAE": "11008"}]
        bp["GoodsDtlsUs44AE"] = [
            {"RegNumberGoodsCarriage": (r["reg_no"] or "-")[:11],
             "OwnedLeasedHiredFlag": r["owned"] if r["owned"] in
             ("OWN", "LEASE", "HIRED") else "OWN",
             "TonnageCapacity": r["tonnage"],
             "HoldingPeriod": r["months"],
             "PresumptiveIncome": max(7500, r["income"])}
            for r in pres["44ae_rows"]]
        bp["PersumptiveInc44AE"] = {
            "TotPersumInc44AE": pres["44ae_income"],
            "SalInterestByFirm": 0,
            "TotalPersumptiveInc": (pres["44ad_income"] + pres["44ada_income"]
                                    + pres["44ae_income"]),
            "IncChargeableUnderBus": (pres["44ad_income"] + pres["44ada_income"]
                                      + pres["44ae_income"]),
        }
    fin_map = {
        "partner_capital": "PartnerMemberOwnCapital", "secured_loans": "SecuredLoans",
        "unsecured_loans": "UnSecuredLoans", "advances": "Advances",
        "sundry_creditors": "SundryCreditors", "other_liabilities": "OthrCurrLiab",
        "total_capital_liabilities": "TotCapLiabilities",
        "fixed_assets": "FixedAssets", "investments": "Investments",
        "inventories": "Inventories", "sundry_debtors": "SundryDebtors",
        "bank_balance": "BalWithBanks", "cash_in_hand": "CashInHand",
        "loans_and_advances": "LoansAndAdvances", "other_assets": "OtherAssets",
        "total_assets": "TotalAssets",
    }
    fin_in = pres.get("financials") or {}
    fin = {}
    for k, out_key in fin_map.items():
        with field_scope("Financial particulars of business", "presumptive.financials"):
            val = _g(fin_in, k)
        if val:
            fin[out_key] = val
    if fin:
        bp["FinanclPartclrOfBusiness"] = fin
    return bp


# ---------------------------------------------------------------------------
# TDS / TCS / IT schedules in the ITR-4 shapes
# ---------------------------------------------------------------------------

def _itr4_tax_schedules(data):
    tp = data.get("tax_paid") or {}
    tds1_rows = []
    for r in (tp.get("tds_on_salary") or []):
        with field_scope("TDS on salary", "tax_paid.tds_on_salary"):
            tds = _g(r, "tds")
        if tds <= 0:
            continue
        tds1_rows.append({
            "EmployerOrDeductorOrCollectDetl": {
                "TAN": _s(r, "tan"),
                "EmployerOrDeductorOrCollecterName": _s(r, "employer_name")},
            "IncChrgSal": _g(r, "salary_income"),
            "TotalTDSSal": tds,
        })
    tds2_rows = []
    for r in (tp.get("tds_others") or []):
        with field_scope("TDS other than salary", "tax_paid.tds_others"):
            claimed = min(_g(r, "tds_claimed"), _g(r, "tds_deducted"))
        if claimed <= 0:
            continue
        tds2_rows.append({
            "TANOfDeductor": _s(r, "tan"),
            "TDSDeducted": _g(r, "tds_deducted"),
            "TDSSection": _s(r, "section", "94A"),
            "TDSClaimed": claimed,
            "GrossAmount": _g(r, "amount_paid"),
            "HeadOfIncome": _s(r, "head_of_income") or "OS",
            "TDSCreditCarriedFwd": 0,
        })
    tds3_rows = []
    for r in (tp.get("tds3") or []):
        with field_scope("TDS on rent", "tax_paid.tds3"):
            claimed = min(_g(r, "tds_claimed"), _g(r, "tds_deducted"))
        if claimed <= 0:
            continue
        row = {
            "PANofTenant": _s(r, "tenant_pan"),
            "TDSDeducted": _g(r, "tds_deducted"),
            "TDSSection": _s(r, "section", "4-IB"),
            "TDSClaimed": claimed,
            "GrossAmount": _g(r, "gross_receipt"),
            "HeadOfIncome": _s(r, "head_of_income") or "HP",
            "TDSCreditCarriedFwd": 0,
        }
        if _s(r, "tenant_aadhaar"):
            row["AadhaarofTenant"] = _s(r, "tenant_aadhaar")
        tds3_rows.append(row)
    tcs_rows = []
    for r in (tp.get("tcs") or []):
        with field_scope("TCS", "tax_paid.tcs"):
            claimed = min(_g(r, "tcs_claimed"), _g(r, "tcs_collected"))
        if claimed <= 0:
            continue
        tcs_rows.append({
            "EmployerOrDeductorOrCollectDetl": {
                "TAN": _s(r, "tan"),
                "EmployerOrDeductorOrCollecterName": _s(r, "collector_name")},
            "Amtfrom26AS": _g(r, "tcs_collected"),
            "TotalTCS": _g(r, "tcs_collected"),
            "AmtTCSClaimedThisYear": claimed,
        })
    challans = []
    for c in (tp.get("challans") or []):
        with field_scope("Advance/SAT challan", "tax_paid.challans"):
            if _g(c, "amount") <= 0:
                continue
            challans.append({"BSRCode": _s(c, "bsr_code"), "DateDep": _s(c, "date"),
                             "SrlNoOfChaln": _g(c, "challan_no"), "Amt": _g(c, "amount")})
    out = {
        "TDSonSalaries": {"TDSonSalary": tds1_rows,
                          "TotalTDSonSalaries": sum(r["TotalTDSSal"] for r in tds1_rows)},
        "TDSonOthThanSals": {"TDSonOthThanSalDtls": tds2_rows,
                             "TotalTDSonOthThanSals": sum(r["TDSClaimed"] for r in tds2_rows)},
        "ScheduleTDS3Dtls": {"TDS3Details": tds3_rows,
                             "TotalTDS3Details": sum(r["TDSClaimed"] for r in tds3_rows)},
        "ScheduleTCS": {"TCS": tcs_rows,
                        "TotalSchTCS": sum(r["AmtTCSClaimedThisYear"] for r in tcs_rows)},
        "ScheduleIT": {"TaxPayment": challans,
                       "TotalTaxPayments": sum(c["Amt"] for c in challans)},
    }
    tds_total = (out["TDSonSalaries"]["TotalTDSonSalaries"]
                 + out["TDSonOthThanSals"]["TotalTDSonOthThanSals"]
                 + out["ScheduleTDS3Dtls"]["TotalTDS3Details"])
    return out, tds_total, out["ScheduleTCS"]["TotalSchTCS"]


# ---------------------------------------------------------------------------
# public builder
# ---------------------------------------------------------------------------

def build_itr4(data: dict, *, creation_info: dict | None = None) -> dict:
    """Build the official ITR-4 JSON plus the computation report."""
    reset_scopes()
    data = copy.deepcopy(data or {})
    warnings: list[str] = []

    personal = data.get("personal", {}) or {}
    filing = data.get("filing", {}) or {}
    opt_out = bool(filing.get("opt_out_new_regime"))
    dob = _s(personal, "dob") or "1990-01-01"

    # Residential status / assessee-status gating, mirroring the official
    # utility macros:
    #  * ITR-4 Sheet1 Worksheet_Change: when ResidentialStatus1 starts with
    #    "NR" (non-resident) the utility runs Lock44AD — locking and CLEARING
    #    the 44AD cells (BP_E1a/E1b/E2a/E2b) and the 44ADA cells
    #    (BP_E3_GR, BP_E4_PI44ADA).  RNOR ("NOR…") is NOT locked: an RNOR is
    #    resident u/s 6 and keeps the presumptive sections.
    #  * Portal validation rule 212: "HUF is not eligible to claim
    #    presumptive income u/s 44ADA."
    residential_status = (_s(personal, "residential_status")
                          or _s(filing, "residential_status") or "RES").upper()[:3]
    status = (_s(personal, "status") or "I").upper()[:1]

    pres = compute_presumptive(data)
    warnings.extend(pres["warnings"])

    if residential_status == "NRI":
        if pres["44ad_rows"] or pres["44ada_rows"]:
            raise DataError(
                "residential status is Non-Resident: presumptive income "
                "u/s 44AD / 44ADA is not available to a non-resident — the "
                "official ITR-4 utility locks and clears those cells for "
                "'NR' (sections 44AD(1)/44ADA(1) apply only to a resident "
                "assessee).  File ITR-3 instead.")
        if pres["44ae_rows"]:
            warnings.append(
                "Residential status is Non-Resident: ITR-4 is meant for "
                "resident assessees (the utility only warns for NR goods-"
                "carriage filers — 'returns for income of non-residents are "
                "required to be filed in ITR 3/5'); consider ITR-3.")
    if status == "H" and pres["44ada_rows"]:
        raise DataError(
            "HUF is not eligible to claim presumptive income u/s 44ADA "
            "(ITR-4 validation rule 212) — remove the 44ADA rows or file "
            "the applicable form.")

    salary_block, hra_block = _build_salary(data, opt_out, warnings)
    exp = data.get("_salary_expansion")
    hp_blocks, hp_total = _build_house_property(data.get("house_properties"),
                                                opt_out, warnings)
    others_block, oth_src_total, ded_57iia = _build_other_sources(
        data.get("other_sources"), opt_out, warnings)
    _build_exempt_income(data.get("exempt_income"), warnings)

    if opt_out and hra_block:
        data["_hra_block"] = hra_block

    # legacy single-line 112A box (same as ITR-1; gain > 1.25 lakh → ITR-2)
    l_in = data.get("ltcg112a") or {}
    with field_scope("LTCG u/s 112A", "ltcg112a"):
        ltcg = max(0, _g(l_in, "sale_consideration") - _g(l_in, "cost_of_acquisition"))
        if ltcg > C.MAX_LTCG_112A:
            warnings.append("LTCG u/s 112A above Rs. 1.25 lakh cannot be reported in "
                            "ITR-4; use ITR-2 (rule 217).")
        ltcg = min(ltcg, C.MAX_LTCG_112A)
    ltcg_for_gti = ltcg

    salary_171 = salary_block["Salary"]
    with field_scope("Income from other sources", "other_sources"):
        interest_income = sum(_g(r, "amount") for r in (data.get("other_sources") or [])
                              if _s(r, "nature") in ("SAV", "IFD", "TAX"))
        savings_interest = sum(_g(r, "amount") for r in (data.get("other_sources") or [])
                               if _s(r, "nature") == "SAV")

    gti_excl_ltcg = (pres["total_income"] + salary_block["IncomeFromSal"]
                     + hp_total + oth_src_total)
    gti_incl_ltcg = gti_excl_ltcg + ltcg_for_gti

    usr_via, elig_via, ded_scheds, via_total = _build_vi_a(
        data, opt_out, gti_excl_ltcg, salary_171,
        _s(personal, "employer_category", "NA"), dob,
        interest_income, savings_interest, ded_57iia > 0, warnings)

    total_income = T.round_off_income(max(0, gti_incl_ltcg - via_total))
    with field_scope("Total income", "presumptive"):
        if total_income > TURNOVER_CAP_ITR4:
            warnings.append(f"Total income Rs. {total_income:,} exceeds the Rs. 50,00,000 "
                            "ceiling for ITR-4 — use ITR-3 instead.")

    tds_sched, tds_total, tcs_total = _itr4_tax_schedules(data)
    filing_date = _s(filing, "filing_date") or str(TODAY())
    return_section = _g(filing, "return_section", 11)
    with field_scope("Relief u/s 89", "relief_89"):
        section89 = _g(data, "relief_89")
    if exp and exp.get("arrears_rows") and not section89:
        dob_year = int(dob[:4]) if dob[:4].isdigit() else None
        w10e = SX.relief_89_working(total_income, exp["arrears_rows"],
                                    regime="old" if opt_out else "new", dob_year=dob_year)
        data["_form10e"] = w10e
        section89 = w10e["relief89"]
        if section89 > 0:
            warnings.append(f"Relief u/s 89 (Form 10E): Rs. {section89:,} computed "
                            "automatically from arrear details.")
    tax = T.compute_tax(total_income=total_income, opt_out_new_regime=opt_out, dob=dob,
                        residential_status=residential_status, status=status,
                        section89=section89, filing_date=filing_date,
                        return_section=return_section, tds=tds_total, tcs=tcs_total,
                        advance_tax_challans=(data.get("tax_paid") or {}).get("challans"),
                        ltcg112a=ltcg,
                        interest_override=data.get("interest_override"))

    # ---------------- document ----------------
    usr_props = _USR_VIA_PROPS
    elig_props = _ELIG_VIA_PROPS
    inc_ded = {
        "IncomeFromBusinessProf": pres["total_income"],
        "GrossSalary": salary_block["GrossSalary"],
        "Salary": salary_block["Salary"],
        "PerquisitesValue": salary_block["PerquisitesValue"],
        "ProfitsInSalary": salary_block["ProfitsInSalary"],
        "AllwncExemptUs10": salary_block["AllwncExemptUs10"],
        "NetSalary": salary_block["NetSalary"],
        "DeductionUs16": salary_block["DeductionUs16"],
        "DeductionUs16ia": salary_block["DeductionUs16ia"],
        "EntertainmntalwncUs16ii": salary_block["EntertainmentAlw16ii"],
        "ProfessionalTaxUs16iii": salary_block["ProfessionalTaxUs16iii"],
        "IncomeFromSal": salary_block["IncomeFromSal"],
        "TotalIncomeChargeableUnHP": hp_total,
        "IncomeOthSrc": oth_src_total + ded_57iia,
        "OthersInc": others_block,
        "DeductionUs57iia": ded_57iia,
        "GrossTotIncome": gti_excl_ltcg,
        "GrossTotIncomeIncLTCG112A": gti_incl_ltcg,
        "UsrDeductUndChapVIA": {k: v for k, v in usr_via.items() if k in usr_props},
        "DeductUndChapVIA": {k: v for k, v in elig_via.items() if k in elig_props},
        "TotalIncome": total_income,
    }
    if hp_blocks:
        inc_ded["PropertyDetails"] = hp_blocks

    tax_comp = {
        "TotalTaxPayable": tax["TotalTaxPayable"],
        "Rebate87A": tax["Rebate87A"],
        "TaxPayableOnRebate": tax["TaxPayableOnRebate"],
        "EducationCess": tax["EducationCess"],
        "GrossTaxLiability": tax["GrossTaxLiability"],
        "NetTaxLiability": tax["NetTaxLiability"],
        "IntrstPay": tax["IntrstPay"],
        "TotTaxPlusIntrstPay": tax["TotTaxPlusIntrstPay"],
    }
    if section89:
        tax_comp["Section89"] = section89

    bank_rows = []
    for b in (data.get("bank_accounts") or []):
        bank_rows.append({
            "IFSCCode": _s(b, "ifsc"), "BankName": _s(b, "bank_name"),
            "BankAccountNo": _s(b, "account_no"),
            "AccountType": _s(b, "account_type", "SB"),
            "UseForRefund": "true" if b.get("use_for_refund") else "false",
        })
    if not bank_rows:
        warnings.append("At least one bank account is required for the return.")

    ver = data.get("verification", {}) or {}
    ver_block = {
        "Declaration": {
            "AssesseeVerName": _s(ver, "name"),
            "FatherName": _s(ver, "father_name") or _s(personal, "father_name"),
            "AssesseeVerPAN": _s(ver, "pan") or _s(personal, "pan"),
        },
        "Capacity": _s(ver, "capacity", "S"),
        "Place": _s(ver, "place"),
    }

    itr4 = {
        "CreationInfo": _creation_block(creation_info),
        "Form_ITR4": {
            "FormName": "ITR-4",
            # Official utility wording, verbatim (incl. its original spelling).
            "Description": UTILITY_FORM_DESCRIPTION["ITR4"],
            "AssessmentYear": "2026", "SchemaVer": "Ver1.0", "FormVer": "Ver1.0",
        },
        "PersonalInfo": _personal_info(data),
        "FilingStatus": _filing_status_itr4(data, warnings),
        "IncomeDeductions": inc_ded,
        "TaxComputation": tax_comp,
        "TaxPaid": {"TaxesPaid": tax["TaxesPaid"],
                    "BalTaxPayable": tax["BalTaxPayable"]},
        "Refund": {"RefundDue": tax["RefundDue"],
                   "BankAccountDtls": {"AddtnlBankDetails": bank_rows}},
        "Verification": ver_block,
    }
    if data.get("_hra_block"):
        itr4["ScheduleEA10_13A"] = data["_hra_block"]
    if ltcg > 0:
        itr4["LTCG112A"] = {
            "TotSaleCnsdrn": _g(l_in, "sale_consideration"),
            "TotCstAcqisn": _g(l_in, "cost_of_acquisition"),
            "LongCap112A": ltcg,
        }
    bp = _schedule_bp(pres)
    if bp:
        itr4["ScheduleBP"] = bp
    for key, value in ded_scheds.items():
        if key in _ITR4_PROPS:
            itr4[key] = value
    for key, block in tds_sched.items():
        row_key = {"TDSonSalaries": "TDSonSalary",
                   "TDSonOthThanSals": "TDSonOthThanSalDtls",
                   "ScheduleTDS3Dtls": "TDS3Details",
                   "ScheduleTCS": "TCS",
                   "ScheduleIT": "TaxPayment"}[key]
        if not block[row_key]:       # every detail array is minItems: 1
            continue
        itr4[key] = block

    doc = {"ITR": {"ITR4": itr4}}
    report = {
        "form": "ITR4", "regime": "old" if opt_out else "new",
        "presumptive": pres,
        "business_income": pres["total_income"],
        "salary_income": salary_block["IncomeFromSal"], "hp_income": hp_total,
        "other_sources_income": oth_src_total,
        "gross_total_income_excl_ltcg": gti_excl_ltcg,
        "gross_total_income_incl_ltcg": gti_incl_ltcg,
        "ltcg112a": ltcg, "total_income": total_income,
        "deductions_eligible": elig_via, "tax": tax, "warnings": warnings,
        "salary_expansion": exp, "form10e": data.get("_form10e"),
    }
    return {"json": doc, "report": report}
